name: deploy-lambda

on: 
  push:
    branches:
        main
  
jobs:
  deploy:
    name: Deploy lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v3

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Create archive
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'bundle.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig .env*'

      - name: Deploy lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-southeast-1
          function_name: switchbot-status-checker
          zip_file: bundle.zip